apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.Values.argocd.certificate.name}} 
  namespace: {{.Values.argocd.namespace}} 
spec:
  dnsNames:
    {{- range .Values.argocd.certificate.dnsNames }}
      - {{ .  }}
    {{- end }}  
  secretName: {{.Values.argocd.certificate.secretName}}
  issuerRef:
    name: {{.Values.cluster_issuer.name}}
    kind: ClusterIssuer
